---
title: "EEB 5301 Homework 3"
author: "Samantha Apgar & Henry Frye"
date: "Spring 2017"
output: 
  tufte::tufte_handout:
    keep_tex: false
---

# Problem 1

## Part a 

Figure 1 shows that interspecifc competition dominates the interaction, the cotinga population will go extinct and the fruit dove population is safe.

The y-intercept of the purple dove line is defined by $\frac{k}{\alpha_{dc}}$ and the x-intercept of the orange cotinga line is defined by $\frac{k}{\alpha_{cd}}$.  Since $k_c=k_d$, we assume k=1 for graphical simplicity. 


```{r, fig.margin = TRUE, echo = FALSE, fig.cap = "Fruit Dove and Spangled Cotingas Phase Diagram"}
library(ggplot2)
library(ggthemes)

#create dataframes
dovedf <- data.frame(xdove = c(0,1), ydove = c(1.25,0))
cotingadf <-  data.frame(xcot = c(0,(1/1.1)),ycot = c(1,0))
bird_df<- cbind(dovedf,cotingadf)

ggplot(bird_df) + geom_line(aes(xdove,ydove), color = 'purple') + 
  geom_line(aes(xcot,ycot), color = 'orange') + 
  theme_tufte() + xlab('Dove Population') + ylab('Cotingas Population') + 
  theme(axis.title.x = element_text(colour = "purple"),
        axis.title.y = element_text(colour = 'orange'))

#Sam, pretty please check my conclusion on this and make sure I didn't get this backward :)
```




## Part b

In Figure 1, the conclusions based on the intercepts of the axes are constrained by the following be true: $\frac{k_c}{\alpha_{cd}}<k_d$ (x-axis) and $k_c< \frac{k_d}{\alpha_{dc}}$ (yaxis). If the carrying capacity of the Cotingas violates these constraints then the conclusions in Part a would change.

# Problem 2

The zero growth isocline is found by setting each population growth rate to zero, $\frac{dN_1}{dt}=0$. The intercepts for the absolute case can be found as:

$$
0=r_1N_1(1-\alpha_{11}N_1-\alpha_{12}N_2)
$$

$$
0= 1-\alpha_{11}N_1-\alpha_{12}N_2
$$

Putting the equation in a linear mx+b format:

$$
N_1 = \frac{ 1 }{ \alpha_{11} }  - \frac{ \alpha_{12} }{ \alpha_{11} } N_2
$$

The intercepts for $N_1$ are $\frac{1}{\alpha_{11}}$ and $\frac{1}{\alpha_{12}}$.


# Problem 3

## Part a

## Part b